version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hashicorp/packer
    versions:
    - 1.6.6
    - 1.7.0
    - 1.7.1
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ansible
    versions:
    - 2.10.0
    - 2.8.8
